GROQ_API_KEY = "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"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.T-UWBswLxJnhZ2Lllj3sH7rB1NE6JXwn6BWBJX-MBQk"
QDRANT_URL = "https://54175d5d-54e4-4f54-ba7b-344d73618c7e.eu-west-2-0.aws.cloud.qdrant.io"
